#------公共配置------
spring:
  sleuth:
    messaging:
      rabbit:
        enabled: true
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true
    refresh:
      enabled: true
    shutdown:
      enabled: false
    health:
      show-details: ALWAYS
    hystrix:
      stream:
        enabled: true


#------差异化配置------
---
spring:
  profiles: dev
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 300
    eureka-server-read-timeout-seconds: 8
    eureka-server-connect-timeout-seconds: 5

---
spring:
  profiles: test
  sleuth:
    sampler:
      probability: 0.5

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 20
    initial-instance-info-replication-interval-seconds: 15
    instance-info-replication-interval-seconds: 10
    eureka-service-url-poll-interval-seconds: 600


---
spring:
  profiles: pro
  sleuth:
    sampler:
      probability: 0.1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    initial-instance-info-replication-interval-seconds: 15
    instance-info-replication-interval-seconds: 10
    eureka-service-url-poll-interval-seconds: 600
